spring:
  datasource:
    url: jdbc:mysql://localhost:3306/sys
    username: root
    password: password
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    show-sql: true
  application:
    name: score-app

hibernate:
  dialect: org.hibernate.dialect.MySQLDialect


logging:
  level:
    root: INFO

server:
  port: 8081

eureka:
  instance:
    lease-renewal-interval-in-seconds: 1
    lease-expiration-duration-in-seconds: 2
  client:
    enabled: true
    service-url:
      defaultZone: http://localhost:8079/eureka

security:
  oauth2:
    resource:
      jwt:
        key-uri: http://localhost:9000/oauth/token_key
